### ISSUE TITLE
Asteroids moving off screen too early.

### ISSUE THREAD

**Issue by gonzalez-adrianj** [danjones5071/capstone-project#3]
With the addition of vertical movement, the asteroids will sometimes move off-screen before they have a chance to reach the player. This should just take some tweaking.

**Comment by gonzalez-adrianj** [comment]
We can either fiddle with restricting the allowed angle range for the randomized velocity based on it's vertical position so that it stays on screen long enough for the player to see it, or possibly have a mechanic where the asteroid's y-axis velocity reflects if it is about to exit the destruction area vertically.

**Comment by danjones5071** [comment]
I just used a conditional to determine where on the y-axis the asteroid is generated. A game object's transform is in the middle of the screen when y = 0. So if y > 0, make sure the vertical velocity is aimed downwards. Otherwise, if y < 0, make sure the vertical velocity is aimed upwards. This seems to have solved the issue. Of course, with the "bouncing" mechanics, it is still possible for the asteroid to be bounced offscreen by another asteroid before reaching the player. But I think this is a pretty cool effect so I'll call this issue closed.
